# These are supported funding model platforms

github: coalrock8642 # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: coalrock8642 # Replace with a single Patreon username
open_collective: # Replace with a single Open Collective username
ko_fi: coalrock8642 # Replace with a single Ko-fi username
tidelift: coalrock8642 # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: coalrock8642 # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: coalrock8642 # Replace with a single Liberapay username
issuehunt: coalrock8642 # Replace with a single IssueHunt username
lfx_crowdfunding: coalrock8642 # Replace with a single LFX Crowdfunding project-name e.g., cloud-foundry
polar: coalrock8642 # Replace with a single Polar username
buy_me_a_coffee: coalrock8642  # Replace with a single Buy Me a Coffee username
custom: coalrock8642 # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
